### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by shimwell**
Develop branch has been ahead of the main branch for a while so perhaps it is time to update the main branch and bring in the various improvements @makeclean and @DanShort12 have made?

This should also update the main pip install which could be handy for users.

The PR would bring the improvments to the main branch:

- improved cmake
- improved openmc connectivity
- fortran bindings

### CODE REVIEW

**Comment by shimwell** [comment]
These tests are great Dan, really nice work

**Comment by DanShort12** [comment]
Thanks @Shimwell - apologies I've been rather sidetracked with other things recently so haven't been able to give this package much attention. I agree it makes sense to get things merged in and I'd certainly be interested to see the automated publish in action!

**Comment by shimwell** [comment]
I noticed we have an issue raised by a user. Perhaps it is worth merging this is. Not sure if it will help this specific case but it is worth a try

**Comment by DanShort12** [comment]
Hi @Shimwell - I suspect merging this will help with a few things as the version on pip will now be quite a way behind the code (and probably the version of OpenMC).

**Pull request merged**
