### PR TITLE
Generate manylinux wheels

### PR DESCRIPTION
**Pull request by DanShort12**
This PR allows the plasma source to be installed without requiring a local build. It makes use of manylinux (as defined under pep 513) to create the build on a container that supports forward compatibility. In particular the Python install used is as provided by the container, not the GitHub version. The Python module auditwheel is used to ensure that the manylinux wheel is created successfully. This should be compatible with any CentOS 7 (or equivalent) and higher Linux operating system, by using the manylinux2014 standard.

### CODE REVIEW

**Comment by DanShort12** [comment]
Looks like the PyPI secrets need to be added for this PR.

**Comment by shimwell** [comment]
Still not sure why this is failing on the test pypi login. I have checked the secrets. Sorry for the delay will keep checking things

**Comment by DanShort12** [comment]
Odd, the user seems to have appropriate permissions on test.pypi.org. Perhaps we should be trying to use an [API token](https://test.pypi.org/help/#apitoken) to do the authentication? Or just try a manual upload using the artifact created from the CI workflow?

**Comment by shimwell** [comment]
Ah I think this might be a permissions thing on github. I'm not sure forks have access to the github secrets for workflows that the forks create. Happy for me to merge then I can try again with another minimal PR to develop to try to trigger the actions. The code is an improvement to what we currently have even without the github actions fully working. Or I can try this https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository#enabling-workflows-for-private-repository-forks

**Comment by DanShort12** [comment]
Sounds worth a try. Like you say there are still a few bits that could be of benefit even if the twine credentials need a bit more of a poke.

**Comment by DanShort12** [comment]
Thanks for merging @Shimwell - looks like the publish to test PyPI has worked. Perhaps that publish step should only run when when a PR is merged then so that the credentials are available?

**Comment by shimwell** [comment]
Yep moving to a trigger on merge only instead of PR and merge as we currently have would solve that little difficulty

Adding you to the repo would also solve it.

I'm keen to keep all the git actions testing so perhaps best to add you to the repo

Any preference anyone?

**Pull request merged**
